export const CONSTANTS = {
  USERNAME_PREFIX: "",

  NAV_LABEL_HOME: "Inicio",
  NAV_LABEL_SEARCH: "Buscar",
  NAV_LABEL_NEW_RECIPE: "Nueva receta",
  NAV_LABEL_MESSAGES: "Mensajes",
  NAV_LABEL_PROFILE: "Perfil",

  TOOLBAR_LABEL_LOGOUT: "Cerrar sesión",

  TITLE_FEED: "Feed",
  TITLE_POST: "Receta",
  TITLE_NEW_POST: "Nueva receta",
  TITLE_SEARCH: "Búsqueda",
  TITLE_CONVERSATIONS: "Chefs / Mensajes",
  TITLE_DM: "Mensaje directo",
  TITLE_PROFILE: "Perfil culinario",
  TITLE_PROFILE_SETTINGS: "Editar perfil",

  LOGIN_TITLE: "Inicia sesión",
  LOGIN_INPUT_USERNAME_PLACEHOLDER: "cool.cheff",
  LOGIN_INPUT_PASSWORD_PLACEHOLDER: "Contraseña",
  LOGIN_BUTTON_TEXT: "Entrar a la cocina",
  LOGIN_HELP_TEXT: "¡Comparte tus recetas con la comunidad!",
  LOGIN_TO_REGISTER: "¿No tienes cuenta? ¡Regístrate!",

  REGISTER_TITLE: "Únete a la cocina",
  REGISTER_BUTTON_TEXT: "Registrarse",
  REGISTER_HELP_TEXT: "Crea tu perfil y empieza a compartir.",
  REGISTER_TO_LOGIN: "¿Ya tienes cuenta? Inicia sesión",

  FEED_SIDEBAR_TITLE: "Explora sabores",
  FEED_SIDEBAR_TEXT:
    "Busca recetas, sigue a otros chefs y guarda tus platos favoritos.",

  MINI_PROFILE_USERNAME_DEFAULT: "default",
  MINI_PROFILE_SUBTITLE_DEFAULT: "default",

  POST_BACK_TO_FEED: "← Volver",
  POST_CHIP_LABEL_PREFIX: "Receta",
  POST_TITLE: "Detalle de la receta",
  POST_BODY: "Ingredientes, pasos y comentarios de la comunidad.",
  POST_LIKE_BUTTON: "Me gusta",
  POST_LIKE_ACTIVE: "Te gusta",
  POST_COMMENTS_TITLE: "Comentarios",
  POST_COMMENT_PLACEHOLDER: "Comparte tu opinión...",
  POST_COMMENT_SEND: "Enviar",
  POST_BAN_BUTTON: "Vetar",
  POST_BANNED_LABEL: "Vetado",
  POST_EDIT_BUTTON: "Editar",

  PROFILE_EDIT_BUTTON: "Editar perfil",
  PROFILE_PUBLISHED_RECIPES: "Recetas publicadas",
  PROFILE_CONNECT_BUTTON: "Conectar",
  PROFILE_FRIEND_BUTTON: "Amigo",
  PROFILE_UNFRIEND_SYMBOL: "X",
  PROFILE_UNFRIEND_ALT: "Dejar de ser amigo",
  PROFILE_SETTINGS_SAVE: "Guardar",
  PROFILE_SETTINGS_CANCEL: "Cancelar",
  PROFILE_SETTINGS_NAME: "Nombre del chef",
  PROFILE_SETTINGS_URL: "Enlace a tu blog o canal",
  PROFILE_SETTINGS_TITLE: "Configurar perfil culinario",
  PROFILE_SETTINGS_SPECIALITY: "Especialidad (italiana, vegana, etc.)",

  SEARCH_INPUT_PLACEHOLDER: "Buscar recetas, chefs o ingredientes",
  SEARCH_POPULAR_TITLE: "Búsquedas populares",
  SEARCH_POPULAR_TEXT:
    "Pizza napolitana, ramen casero, tiramisú, meal prep saludable.",
  SEARCH_SECTION_CHEFS: "Chefs",
  SEARCH_SECTION_RECIPES: "Recetas",
  LOADING_TEXT: "Cargando...",

  DM_INPUT_PLACEHOLDER: "Comparte un truco o pregunta...",
  DM_SEND_BUTTON: "Enviar",

  NOT_FOUND_404: "404",
  NOT_FOUND_TEXT: "Página no encontrada.",
  NOT_FOUND_BACK_BUTTON: "Volver al feed de recetas",

  CURRENT_USER_ID: "me",

  POST_CARD_DEFAULT_USERNAME: "@defaultChef",
  POST_CARD_DEFAULT_CAPTION: "default caption",
  POST_CARD_FALLBACK_IMAGE_TEXT: "Foto del plato",
  NO_RESULTS_TEXT: "No hay resultados.",

  NEW_POST_HEADER: "Crear nueva receta",
  NEW_POST_TITLE_LABEL: "Título",
  NEW_POST_TITLE_PLACEHOLDER: "Título de la receta",
  NEW_POST_IMAGES_LABEL: "Imágenes",
  NEW_POST_SELECT_BUTTON: "Elegir archivos",
  NEW_POST_NO_FILES_SELECTED: "Ningún archivo seleccionado",
  NEW_POST_ONE_FILE_SELECTED: "1 archivo seleccionado",
  NEW_POST_MULTIPLE_FILES_SELECTED: "archivos seleccionados",
  NEW_POST_REMOVE_IMAGE: "Eliminar",
  NEW_POST_REORDER_IMAGE_ARIA: "Reordenar imagen",
  NEW_POST_ONLY_IMAGES_ERROR: "Solo se permiten archivos de imagen.",
  NEW_POST_DESCRIPTION_LABEL: "Descripción",
  NEW_POST_DESCRIPTION_PLACEHOLDER: "Resumen breve de la receta",
  NEW_POST_BODY_LABEL: "Cuerpo",
  NEW_POST_BODY_PLACEHOLDER: "Describe la receta, pasos, ingredientes...",
  NEW_POST_TAGS_LABEL: "Etiquetas",
  NEW_POST_TAG_PLACEHOLDER: "Añadir etiqueta...",
  NEW_POST_TAG_ADD_BUTTON: "Añadir",
  NEW_POST_TAG_REMOVE: "x",
  NEW_POST_SAVE_BUTTON: "Guardar receta",
  NEW_POST_REQUIRED_ERROR: "Debes indicar título, descripción y cuerpo.",
};
